// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

type BrowserSupabaseClient = SupabaseClient<Database>;

const missingSupabaseConfigMessage =
  'Missing Supabase environment variable(s): SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY. Demo mode will use local fallback data.';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createEmptyQuery() {
  const result = Promise.resolve({ data: [], error: null });
  const query: any = {
    select: () => query,
    order: () => query,
    eq: () => query,
    in: () => query,
    limit: () => query,
    insert: () => query,
    update: () => query,
    delete: () => query,
    upsert: () => query,
    single: () => Promise.resolve({ data: null, error: null }),
    then: result.then.bind(result),
    catch: result.catch.bind(result),
    finally: result.finally.bind(result),
  };
  return query;
}

function createUnavailableSupabaseClient() {
  return {
    auth: {
      getUser: async () => ({ data: { user: null }, error: null }),
      getSession: async () => ({ data: { session: null }, error: null }),
      onAuthStateChange: () => ({
        data: {
          subscription: {
            unsubscribe: () => {},
          },
        },
      }),
      signInWithPassword: async () => ({ data: { user: null, session: null }, error: new Error(missingSupabaseConfigMessage) }),
      signUp: async () => ({ data: { user: null, session: null }, error: new Error(missingSupabaseConfigMessage) }),
      resetPasswordForEmail: async () => ({ data: {}, error: new Error(missingSupabaseConfigMessage) }),
      updateUser: async () => ({ data: { user: null }, error: new Error(missingSupabaseConfigMessage) }),
      signOut: async () => ({ error: null }),
    },
    from: () => createEmptyQuery(),
    rpc: async () => ({ data: null, error: new Error(missingSupabaseConfigMessage) }),
    storage: {
      from: () => ({
        upload: async () => ({ data: null, error: new Error(missingSupabaseConfigMessage) }),
        createSignedUrl: async () => ({ data: null, error: new Error(missingSupabaseConfigMessage) }),
      }),
    },
  } as unknown as BrowserSupabaseClient;
}


function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.warn(`[Supabase] ${missingSupabaseConfigMessage}`);
    return createUnavailableSupabaseClient();
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: BrowserSupabaseClient | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as BrowserSupabaseClient, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
